project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    section: "PSY 360"
    contents:
      - section: "Lectures"
        contents:
        - href: "welcome_viewer.qmd"
        - href: "lec2_viewer.qmd"
        - href: "lec3_viewer.qmd"
        - href: "lec4_viewer.qmd"
        - href: "lec5_viewer.qmd"
        - href: "lec6_viewer.qmd"
      - section: "Labs"
        contents:
        - href: "lab1_viewer.qmd"
        - href: "lab3_viewer.qmd"
  title: "PSY 360: Research Methods"
  navbar:
    background: "#46567B"
    left:
      - href: index.qmd

format:
  html:
    theme: [default, custom.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual
